import { BusinessArchitecture } from './architecture';

export interface DetailedBusinessModel {
  id: string;
  name: string;
  model: string;
  category: string;
  industry: 'HEALTHCARE' | 'GYM' | 'RESTAURANT' | 'RENTAL' | 'REPAIR' | 'RETAIL';
  shopType: 'healthcare' | 'gym' | 'restaurant' | 'rental' | 'repair' | 'retail';
  arch: BusinessArchitecture;
  emoji: string;
  badge: string;
  tagline: string;
  description: string;
  keyFeatures: string[];
  sampleGst: string;
  sampleEmailPrefix: string;
  sampleEmailDomain: string;
  samplePhone: string;
  sampleAddress: string;
  taxState: 'INTRA_STATE' | 'INTER_STATE';
}

export const DETAILED_BUSINESS_CATALOG: DetailedBusinessModel[] = [
  // =========================================================================
  // 1. HEALTHCARE & MEDICAL (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'healthcare_multispeciality',
    name: 'Apollo Care Multi-Speciality Hospital',
    model: 'Multi-Speciality Hospital & Trauma Center',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '🏥',
    badge: 'Tertiary Hospital',
    tagline: 'Full-spectrum inpatient, outpatient, surgical and diagnostic hospital',
    description: 'Equipped with electronic health records (EHR), multi-doctor rosters, appointment scheduling, and OPD fee collection.',
    keyFeatures: ['EHR Patient Records', 'Multi-Speciality Doctor Roster', 'Double-Booking Guard', 'OPD Fee Invoicing'],
    sampleGst: '07AAACH1234Q1Z2',
    sampleEmailPrefix: 'hospital.admin',
    sampleEmailDomain: 'apollocare.org',
    samplePhone: '+91 98111 22334',
    sampleAddress: 'Plot 42, Health Enclave, Ring Road, New Delhi',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'healthcare_dental',
    name: 'Dr. Smiles Orthodontic & Dental Center',
    model: 'Dental Care & Orthodontic Clinic',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '🦷',
    badge: 'Dental Clinic',
    tagline: 'Specialized dental surgeries, alignments and cosmetic dentistry',
    description: 'Manages dental chair bookings, patient tooth history charts, dental procedure fees, and consultation schedules.',
    keyFeatures: ['Dental Chair Appointments', 'Patient Procedure History', 'Specialist Consultations', 'Automated SMS Reminders'],
    sampleGst: '27AABCD3456K1Z9',
    sampleEmailPrefix: 'dental.care',
    sampleEmailDomain: 'drsmiles.in',
    samplePhone: '+91 98202 33445',
    sampleAddress: 'Shop 14, Sunrise Galleria, Bandra West, Mumbai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'healthcare_pathology',
    name: 'Precision Diagnostics & Pathology Lab',
    model: 'Pathology & Diagnostic Imaging Center',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '🔬',
    badge: 'Diagnostic Lab',
    tagline: 'High-precision blood chemistry, histology and medical imaging',
    description: 'Manages lab test catalogs, patient sample intakes, test queue status, and billing for clinical pathology.',
    keyFeatures: ['Diagnostic Test Catalog', 'Sample Collection Intake', 'EHR Test Results', 'Billing & Test Receipts'],
    sampleGst: '29AABCP5678M1Z3',
    sampleEmailPrefix: 'lab.director',
    sampleEmailDomain: 'precisionlab.io',
    samplePhone: '+91 98450 44556',
    sampleAddress: '102 Bio-Science Tower, Indiranagar, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'healthcare_pediatric',
    name: 'Blossom Mother & Child Health Clinic',
    model: 'Pediatric & Maternity Polyclinic',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '👶',
    badge: 'Pediatric Care',
    tagline: 'Comprehensive child healthcare, neonatal care and vaccination',
    description: 'Tracks developmental growth charts, pediatric doctor schedules, immunizations, and child health folders.',
    keyFeatures: ['Immunization Tracking', 'Pediatrician Roster', 'Growth Milestone Folders', 'Consultation Queue'],
    sampleGst: '36AABCW7890N1Z7',
    sampleEmailPrefix: 'pediatric.lead',
    sampleEmailDomain: 'blossomclinic.com',
    samplePhone: '+91 98765 55667',
    sampleAddress: 'Road 36, Jubilee Hills, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'healthcare_ophthalmology',
    name: 'VisionCraft Advanced Eye Care & Laser Lab',
    model: 'Ophthalmology & Refractive Eye Clinic',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '👁️',
    badge: 'Eye Hospital',
    tagline: 'State-of-the-art vision correction, retina care and cataract clinic',
    description: 'Handles eye diagnostics, ophthalmologist time-slots, patient prescription vision cards, and surgical consultations.',
    keyFeatures: ['Optical Prescription Cards', 'Eye Surgeon Schedules', 'Refractive Diagnostics', 'Surgical Billing'],
    sampleGst: '33AABCV9012P1Z1',
    sampleEmailPrefix: 'eyecare.admin',
    sampleEmailDomain: 'visioncraft.org',
    samplePhone: '+91 98401 66778',
    sampleAddress: '4th Floor, MediPlaza, Anna Nagar, Chennai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'healthcare_wellness',
    name: 'AyurVeda Holistic Wellness & Therapy Retreat',
    model: 'Ayurvedic & Alternative Medicine Center',
    category: 'Healthcare & Medical',
    industry: 'HEALTHCARE',
    shopType: 'healthcare',
    arch: 'HEALTHCARE',
    emoji: '🌿',
    badge: 'Wellness Center',
    tagline: 'Panchakarma therapies, holistic naturopathy and herbal medicine',
    description: 'Organizes therapeutic session appointments, vaidya practitioner notes, diet regimens, and treatment billing.',
    keyFeatures: ['Therapy Slot Booking', 'Vaidya Consultations', 'Holistic Regimen Folders', 'Herbal Treatment Invoices'],
    sampleGst: '32AABCA1234Q1Z5',
    sampleEmailPrefix: 'ayur.retreat',
    sampleEmailDomain: 'ayurvedawellness.in',
    samplePhone: '+91 98470 77889',
    sampleAddress: 'Lakeview Valley Road, Fort Kochi, Kerala',
    taxState: 'INTRA_STATE',
  },

  // =========================================================================
  // 2. GYM, FITNESS & ATHLETIC CLUBS (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'gym_crossfit',
    name: 'IronPulse High-Intensity CrossFit Box',
    model: 'Functional Fitness & CrossFit Arena',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '🏋️',
    badge: 'CrossFit Box',
    tagline: 'Olympic weightlifting, metabolic conditioning and functional strength',
    description: 'Features WOD attendance, drop-in passes, multi-month athlete memberships, and trainer allocations.',
    keyFeatures: ['WOD Attendance Check-in', 'Athlete Membership Tiers', 'Drop-In Passes', 'Freeze Day Management'],
    sampleGst: '29AABCI5678R1Z5',
    sampleEmailPrefix: 'coach.lead',
    sampleEmailDomain: 'ironpulse.fit',
    samplePhone: '+91 98800 88990',
    sampleAddress: '88 Industrial Layout, Koramangala 4th Block, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'gym_247_fitness',
    name: 'Titanium 24/7 Commercial Fitness Club',
    model: '24/7 Commercial Fitness & Bodybuilding Gym',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '💪',
    badge: 'Commercial Gym',
    tagline: 'Continuous 24-hour workout access, cardio zone and heavy iron room',
    description: 'Equipped with turnstile attendance tracking, annual and quarterly membership contracts, and freeze calculators.',
    keyFeatures: ['Turnstile Check-In Log', 'Annual & Quarterly Plans', 'Membership Freeze Guard', 'Trainer Roster'],
    sampleGst: '27AABCT9012S1Z4',
    sampleEmailPrefix: 'club.manager',
    sampleEmailDomain: 'titaniumfitness.com',
    samplePhone: '+91 98200 11223',
    sampleAddress: 'Level 2, Metro Grand Mall, Andheri East, Mumbai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'gym_yoga_pilates',
    name: 'ZenPulse Hot Yoga & Reformer Pilates Studio',
    model: 'Boutique Yoga & Pilates Studio',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '🧘',
    badge: 'Boutique Studio',
    tagline: 'Infrared hot yoga, clinical reformer pilates and sound meditation',
    description: 'Manages class attendance, session credits, instructor rosters, and flexible student freeze policies.',
    keyFeatures: ['Class Session Attendance', 'Reformer Slot Bookings', 'Credit Pass Expiries', 'Instructor Schedules'],
    sampleGst: '07AABCZ3456T1Z8',
    sampleEmailPrefix: 'studio.admin',
    sampleEmailDomain: 'zenpulseyoga.org',
    samplePhone: '+91 98100 22334',
    sampleAddress: 'B-12 Hauz Khas Enclave, New Delhi',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'gym_mma_combat',
    name: 'Apex Combat MMA & Striking Academy',
    model: 'Mixed Martial Arts & Boxing Dojo',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '🥊',
    badge: 'Combat Dojo',
    tagline: 'Brazilian Jiu-Jitsu, Muay Thai striking, wrestling and cage fitness',
    description: 'Tracks belt ranking records, fighter attendance rosters, private coach sessions, and team plan renewals.',
    keyFeatures: ['Fighter Attendance Log', 'Belt & Rank Tracking', 'Coach Private Sessions', 'Fight Camp Passes'],
    sampleGst: '36AABCA7890U1Z2',
    sampleEmailPrefix: 'sensei.admin',
    sampleEmailDomain: 'apexcombat.io',
    samplePhone: '+91 98660 33445',
    sampleAddress: 'Plot 15, Hitech City Main Road, Madhapur, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'gym_aquatic_sports',
    name: 'AquaFit Olympic Swimming & Hydro Arena',
    model: 'Aquatic Center & Swim Academy',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '🏊',
    badge: 'Aquatic Center',
    tagline: 'Olympic heated pools, lane reservations and competitive coaching',
    description: 'Controls lane turnstile access, swim coach rosters, seasonal membership freezes, and locker assignments.',
    keyFeatures: ['Lane Access Control', 'Swim Coach Sessions', 'Seasonal Membership Freeze', 'Locker & Towel Records'],
    sampleGst: '33AABCS1234V1Z6',
    sampleEmailPrefix: 'aquatics.lead',
    sampleEmailDomain: 'aquafitarena.com',
    samplePhone: '+91 98410 44556',
    sampleAddress: 'Sports Village, ECR Highway, Thiruvanmiyur, Chennai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'gym_sports_rehab',
    name: 'AthleticEdge High-Performance Sports Lab',
    model: 'Sports Science & Rehabilitation Gym',
    category: 'Gym & Fitness',
    industry: 'GYM',
    shopType: 'gym',
    arch: 'GYM',
    emoji: '⚡',
    badge: 'Sports Science Lab',
    tagline: 'Biomechanics analysis, injury recovery and elite athlete conditioning',
    description: 'Integrates recovery bay check-ins, physio therapist plans, and athlete rehabilitation subscriptions.',
    keyFeatures: ['Athlete Conditioning Plans', 'Physio Rehab Check-in', 'Biomechanics Sessions', 'Medical Freeze Support'],
    sampleGst: '27AABCE5678W1Z0',
    sampleEmailPrefix: 'director.sports',
    sampleEmailDomain: 'athleticedge.in',
    samplePhone: '+91 98210 55667',
    sampleAddress: 'Olympia House, Senapati Bapat Marg, Pune',
    taxState: 'INTRA_STATE',
  },

  // =========================================================================
  // 3. RESTAURANT, DINING & FOOD BEVERAGE (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'restaurant_finedining',
    name: 'The Golden Truffle French Bistro & Lounge',
    model: 'Fine Dining Bistro & Wine Cellar',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '🍽️',
    badge: 'Fine Dining',
    tagline: 'Michelin-inspired tasting menus, sommelier pairings and white-glove service',
    description: 'Equipped with interactive dining table management, multi-course KOT firing, waiter assignments, and bill splits.',
    keyFeatures: ['Visual Table Floor Plan', 'Multi-Course KOT Firing', 'Table Status Lifecycle', 'Split-Bill & Tip Settle'],
    sampleGst: '27AABCR9012S1Z8',
    sampleEmailPrefix: 'dining.gm',
    sampleEmailDomain: 'goldentruffle.com',
    samplePhone: '+91 98205 66778',
    sampleAddress: 'Shop 12, Heritage Courtyard, Colaba, Mumbai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'restaurant_artisan_cafe',
    name: 'Le Petit Sourdough Bakery & Roastery Cafe',
    model: 'Artisan Bakery & Specialty Coffee Roastery',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '☕',
    badge: 'Artisan Cafe',
    tagline: 'Single-origin espresso, fermented sourdough loaves and Viennoiserie',
    description: 'Fast-paced counter orders, barista bar kitchen tickets (BOT), indoor/outdoor table flags, and pastry sales.',
    keyFeatures: ['Counter & Table Orders', 'Barista Kitchen Tickets (BOT)', 'Pastry & Beverage Menu', 'Instant QR Payments'],
    sampleGst: '29AABCB3456X1Z4',
    sampleEmailPrefix: 'roastery.admin',
    sampleEmailDomain: 'lepetitcafe.in',
    samplePhone: '+91 98455 77889',
    sampleAddress: '74 Lavelle Road, Shanthala Nagar, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'restaurant_woodfired_pizza',
    name: 'Bella Napoli Woodfired Trattoria',
    model: 'Authentic Italian Pizzeria & Trattoria',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '🍕',
    badge: 'Pizzeria Trattoria',
    tagline: 'Neapolitan 90-second pizza, handmade pasta and antipasti boards',
    description: 'Direct pizza station KOT routing, delivery packaging toggles, table occupancy meters, and beverage addons.',
    keyFeatures: ['Pizza Oven KOT Routing', 'Dine-In & Takeout Modes', 'Table Turnover Tracking', 'Modifier & Crust Addons'],
    sampleGst: '07AABCP7890Y1Z8',
    sampleEmailPrefix: 'pizzaiolo.admin',
    sampleEmailDomain: 'bellanapoli.in',
    samplePhone: '+91 98115 88990',
    sampleAddress: 'M-Block Market, Greater Kailash 2, New Delhi',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'restaurant_qsr_burger',
    name: 'SmashCraft Gourmet Burgers & Shakes',
    model: 'High-Velocity Fast Casual & QSR Joint',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '🍔',
    badge: 'QSR Fast Casual',
    tagline: 'Crispy smash patties, brioche buns, loaded fries and custard shakes',
    description: 'High-speed order numbering, dual grill/fryer kitchen display ticket splits, and counter collection boards.',
    keyFeatures: ['Order Number Sequence', 'Kitchen Prep Display (KDS)', 'Express Counter Billing', 'Combo & Addon Upselling'],
    sampleGst: '36AABCS1234Z1Z2',
    sampleEmailPrefix: 'qsr.ops',
    sampleEmailDomain: 'smashcraft.io',
    samplePhone: '+91 98760 99001',
    sampleAddress: 'Cyber Food Plaza, Gachibowli, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'restaurant_rooftop_brewery',
    name: 'Skyline Craft Brewery & Smokehouse',
    model: 'Rooftop Microbrewery & Pub',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '🍺',
    badge: 'Microbrewery Pub',
    tagline: 'Fresh craft taps, slow-smoked BBQ and panoramic city sunset views',
    description: 'Handles 40+ rooftop tables across open-air and indoor sections, bartender KOTs, and table transfer merges.',
    keyFeatures: ['Sectioned Floor Matrix', 'Bar Tap Order Tickets', 'Table Transfer & Merging', 'Dynamic Cover Billing'],
    sampleGst: '27AABCQ5678A1Z6',
    sampleEmailPrefix: 'brewmaster.admin',
    sampleEmailDomain: 'skylinebrew.com',
    samplePhone: '+91 98208 00112',
    sampleAddress: 'Rooftop Level 11, Palladium Mall, Lower Parel, Mumbai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'restaurant_cloud_kitchen',
    name: 'ChefCo Multi-Brand Virtual Cloud Kitchen',
    model: 'Cloud Kitchen & Delivery Hub',
    category: 'Restaurant & Dining',
    industry: 'RESTAURANT',
    shopType: 'restaurant',
    arch: 'RESTAURANT',
    emoji: '🥡',
    badge: 'Cloud Kitchen',
    tagline: 'Centralized production kitchen powering 5 delivery culinary brands',
    description: 'Aggregates multi-brand delivery tickets, kitchen cook times, packaging checklist validation, and dispatch queues.',
    keyFeatures: ['Multi-Brand Ticket Routing', 'Cook Time Timers', 'Packaging Checklist Verification', 'Courier Dispatch Queue'],
    sampleGst: '33AABCK9012B1Z0',
    sampleEmailPrefix: 'cloud.kitchen',
    sampleEmailDomain: 'chefcovirtual.in',
    samplePhone: '+91 98405 11223',
    sampleAddress: 'Unit 4, Central Commissary Hub, Guindy, Chennai',
    taxState: 'INTRA_STATE',
  },

  // =========================================================================
  // 4. EQUIPMENT RENTAL & VEHICLE FLEET (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'rental_cinema_gear',
    name: 'CinePro 8K Cameras & Anamorphic Rentals',
    model: 'Cinema, Camera & Studio Lighting Rentals',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🎥',
    badge: 'Cinema Rental',
    tagline: 'RED V-Raptor, ARRI Alexa 35, Cooke Anamorphics and Aputure lights',
    description: 'Guaranteed overlap conflict detection, security deposit hold calculation, serial asset tracking, and late fees.',
    keyFeatures: ['Date Collision Prevention', 'Security Deposit Returns', 'Serial Kit Tracking', 'Overdue Late Fee Calculator'],
    sampleGst: '06AABCS3456T1Z1',
    sampleEmailPrefix: 'cinepro.rental',
    sampleEmailDomain: 'cineprogear.rent',
    samplePhone: '+91 98118 22334',
    sampleAddress: 'Sector 18, Film & Commercial Hub, Gurgaon',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'rental_luxury_fleet',
    name: 'Velocita Prestige Luxury Fleet & Chauffeur Hire',
    model: 'Luxury Cars & Executive SUV Fleet',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🏎️',
    badge: 'Fleet Rental',
    tagline: 'Mercedes Maybach, Porsche 911, Range Rover and BMW 7-Series self-drive',
    description: 'Schedules vehicle bookings across dates, inspects odometer condition upon return, and settles deposit refunds.',
    keyFeatures: ['Vehicle Fleet Schedule', 'Overlap Date Guard', 'Vehicle Condition Notes', 'Refundable Deposit Escrow'],
    sampleGst: '27AABCV7890C1Z4',
    sampleEmailPrefix: 'fleet.director',
    sampleEmailDomain: 'velocitafleet.com',
    samplePhone: '+91 98209 33445',
    sampleAddress: 'Domestic Airport Terminal Approach Road, Vile Parle, Mumbai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'rental_heavy_equipment',
    name: 'Apex Build Heavy Machinery & Earthmover Hire',
    model: 'Construction & Industrial Plant Hire',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🚜',
    badge: 'Heavy Plant Hire',
    tagline: 'JCB Backhoes, CAT Excavators, Cranes and Diesel Generators',
    description: 'Long-term contractor asset reservations, machine hours tracking, scheduled maintenance, and project return logs.',
    keyFeatures: ['Contractor Booking Ledger', 'Machine Serial Verification', 'Damage & Condition Notes', 'Late Return Penalties'],
    sampleGst: '29AABCJ1234D1Z8',
    sampleEmailPrefix: 'heavyplant.hire',
    sampleEmailDomain: 'apexmachinery.in',
    samplePhone: '+91 98459 44556',
    sampleAddress: 'Plot 77, Peenya Industrial Area Phase 2, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'rental_event_av_stage',
    name: 'Starlight Concert Sound, Truss & LED Wall Hire',
    model: 'Event Production & Stage Lighting Rental',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🔊',
    badge: 'AV & Event Hire',
    tagline: 'Line-array speakers, motorized moving head lights and 4K LED backdrops',
    description: 'Organizes event gear packages, booking start/end timestamps, warehouse dispatch inspection, and damaged part fees.',
    keyFeatures: ['Event Equipment Roster', 'Date-Range Lockout', 'Deposit Reimbursement', 'Dispatched Kit Checklist'],
    sampleGst: '36AABCE5678E1Z2',
    sampleEmailPrefix: 'events.staging',
    sampleEmailDomain: 'starlightav.io',
    samplePhone: '+91 98669 55667',
    sampleAddress: 'Road 12, Banjara Hills Exhibition Zone, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'rental_motorcycle_tour',
    name: 'Nomad Moto Himalayan Touring Bike Rentals',
    model: 'Adventure Motorcycle & Touring Gear Rentals',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🏍️',
    badge: 'Motorcycle Hire',
    tagline: 'Royal Enfield Himalayan 450, BMW GS and riding gear expeditions',
    description: 'Manages bike fleet availability calendars, security deposits, riding gear add-on rentals, and return checklists.',
    keyFeatures: ['Bike Availability Roster', 'Helmet & Jacket Add-ons', 'Trip Date Collision Guard', 'Deposit Settlement'],
    sampleGst: '02AABCN9012F1Z6',
    sampleEmailPrefix: 'nomad.tours',
    sampleEmailDomain: 'nomadmoto.in',
    samplePhone: '+91 98160 66778',
    sampleAddress: 'Mall Road, Old Manali, Himachal Pradesh',
    taxState: 'INTER_STATE',
  },
  {
    id: 'rental_medical_devices',
    name: 'CareBreeze Medical Oxygen & Home ICU Equipment Hire',
    model: 'Medical Devices & Home Health Equipment Hire',
    category: 'Rental & Fleet Hire',
    industry: 'RENTAL',
    shopType: 'rental',
    arch: 'RENTAL',
    emoji: '🫁',
    badge: 'Medical Hire',
    tagline: 'Philips Oxygen Concentrators, CPAP/BiPAP units and Motorized Hospital Beds',
    description: 'Critical patient device tracking, monthly recurring rental extensions, sanitized status, and deposit management.',
    keyFeatures: ['Patient Equipment Tracking', 'Sanitization Status Verification', 'Monthly Renewal Calculator', 'Zero-Conflict Dates'],
    sampleGst: '27AABCM3456G1Z0',
    sampleEmailPrefix: 'carebreeze.ops',
    sampleEmailDomain: 'carebreezemed.com',
    samplePhone: '+91 98204 77889',
    sampleAddress: 'Health Arcade, LBS Marg, Mulund West, Mumbai',
    taxState: 'INTRA_STATE',
  },

  // =========================================================================
  // 5. HARDWARE REPAIR, DIAGNOSTICS & LAB (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'repair_smartphone_tablet',
    name: 'TechFix Micro-Soldering & Device Lab',
    model: 'Smartphone, Tablet & Watch Repair Lab',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '🔧',
    badge: 'Mobile Lab',
    tagline: 'Chip-level iPhone logic boards, OLED refurbishing and micro-soldering',
    description: 'Complete repair intake job-card creation, customer fault descriptions, technician assignments, parts and labor cost sheets.',
    keyFeatures: ['Intake Job Card Sequence', 'Multi-Stage Repair Lifecycle', 'Parts + Labor Cost Breakdown', 'Customer Delivery Notification'],
    sampleGst: '36AABCT7890U1Z4',
    sampleEmailPrefix: 'repair.lead',
    sampleEmailDomain: 'techfixlab.io',
    samplePhone: '+91 97665 44332',
    sampleAddress: 'B-Block, Electronic City, Cyberabad, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'repair_laptop_macbook',
    name: 'SiliconLogic MacBook & PC Diagnostic Center',
    model: 'MacBook & High-End PC Hardware Diagnostics',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '💻',
    badge: 'MacBook Repair',
    tagline: 'Apple Silicon M1/M2/M3 component repair, liquid spill recovery and GPU reballing',
    description: 'Tracks serial numbers, diagnostic status milestones (DIAGNOSING to READY), technician time logs, and invoices.',
    keyFeatures: ['Serial Number Hardware Registry', 'Liquid Spill Diagnostic Log', 'Parts Inventory Consumption', 'Warranty Repair Stamps'],
    sampleGst: '29AABCS1234H1Z8',
    sampleEmailPrefix: 'mac.specialist',
    sampleEmailDomain: 'siliconlogic.in',
    samplePhone: '+91 98451 88990',
    sampleAddress: '42 Brigade Road, Ashok Nagar, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'repair_auto_garage',
    name: 'TurboTune Multi-Brand Auto Care Garage',
    model: 'Automotive Mechanical & Electronic Service Garage',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '🚗',
    badge: 'Auto Garage',
    tagline: 'ECU tuning, engine rebuilds, periodic servicing and electronic diagnostics',
    description: 'Creates vehicle service cards, tracks odometer readings, itemizes engine oil/filters, labor costs, and delivery approvals.',
    keyFeatures: ['Vehicle Job Card Form', 'Technician Bay Assignment', 'OEM Spare Parts Accounting', 'Final Delivery Billing'],
    sampleGst: '27AABCT5678I1Z2',
    sampleEmailPrefix: 'service.advisor',
    sampleEmailDomain: 'turbotuneauto.com',
    samplePhone: '+91 98212 99001',
    sampleAddress: 'Gala 18, Auto Hub Industrial Estate, Kothrud, Pune',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'repair_superbike_garage',
    name: 'Apex Moto Performance Tuning Workshop',
    model: 'Superbike & Two-Wheeler Tuning Workshop',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '🏍️',
    badge: 'Superbike Garage',
    tagline: 'Suspension re-valving, dyno runs, brake overhauls and racing setups',
    description: 'Specialist job tickets for high-performance bikes, parts catalog integration, technician diagnostics, and total invoicing.',
    keyFeatures: ['Dyno & Tuning Job Cards', 'Specialist Tech Allocation', 'Performance Parts Pricing', 'Delivery Handover Settle'],
    sampleGst: '07AABCM9012J1Z6',
    sampleEmailPrefix: 'lead.mechanic',
    sampleEmailDomain: 'apexmotopune.in',
    samplePhone: '+91 98105 00112',
    sampleAddress: 'K-Block Okhla Industrial Area Phase 3, New Delhi',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'repair_drone_robotics',
    name: 'AeroFix Precision Drone & Avionics Lab',
    model: 'Drone & Industrial Robotics Maintenance',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '🛸',
    badge: 'Drone Lab',
    tagline: 'DJI Enterprise, agricultural drones, flight controllers and gimbal calibration',
    description: 'Records aircraft crash diagnostics, brushless motor tests, firmware re-flashing, and parts warranty tracking.',
    keyFeatures: ['Avionics Diagnostic Sheet', 'Gimbal & Motor Testing', 'Component Replacement Billing', 'Flight Test Signoff'],
    sampleGst: '33AABCD3456K1Z0',
    sampleEmailPrefix: 'avionics.lead',
    sampleEmailDomain: 'aerofixdrones.io',
    samplePhone: '+91 98409 11223',
    sampleAddress: 'AeroPark Tech Enclave, Guindy, Chennai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'repair_hvac_appliances',
    name: 'CoolCraft Commercial HVAC & Refrigeration Lab',
    model: 'Commercial HVAC, Chiller & Appliance Hub',
    category: 'Repair & Diagnostics',
    industry: 'REPAIR',
    shopType: 'repair',
    arch: 'REPAIR',
    emoji: '❄️',
    badge: 'HVAC Lab',
    tagline: 'Inverter compressor repairs, refrigerant leak tests and PCB diagnostics',
    description: 'Dispatches technician job cards, diagnostic checklists, compressor replacement costs, and customer receipts.',
    keyFeatures: ['Appliance Job Card Registry', 'Refrigerant & Parts Costing', 'Field Tech Work Orders', 'Warranty Stamp Issuance'],
    sampleGst: '27AABCC7890L1Z4',
    sampleEmailPrefix: 'coolcraft.admin',
    sampleEmailDomain: 'coolcraftservice.com',
    samplePhone: '+91 98207 22334',
    sampleAddress: 'Industrial Gala 9, Thane West, Mumbai',
    taxState: 'INTRA_STATE',
  },

  // =========================================================================
  // 6. RETAIL, GROCERY & SUPERMARKETS (6 DISTINCT BUSINESS MODELS)
  // =========================================================================
  {
    id: 'retail_supermarket',
    name: 'DailyFresh HyperMart & Supermarket',
    model: 'Supermarket & Fast Grocery HyperMart',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '🛒',
    badge: 'Supermarket',
    tagline: 'High-velocity FMCG, dairy, produce, packaged foods and household supplies',
    description: 'Equipped with rapid barcode scanning, till drawer management, hold-bill queue, supplier POs, and GST receipts.',
    keyFeatures: ['High-Speed Barcode Terminal', 'Hold & Resume Bill Stack', 'Inventory Low-Stock Alerts', 'Split-Tender Payments'],
    sampleGst: '27AABCD2345V1Z9',
    sampleEmailPrefix: 'grocery.admin',
    sampleEmailDomain: 'dailyfresh.in',
    samplePhone: '+91 98200 33445',
    sampleAddress: 'Ring Road 5, North Extension, Pune',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'retail_organic_produce',
    name: 'EarthHarvest Organic Farm Market & Pantry',
    model: 'Farm-to-Table Organic & Specialty Foods',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '🥑',
    badge: 'Organic Market',
    tagline: 'Certified chemical-free vegetables, cold-pressed oils and artisanal honey',
    description: 'Weighing-scale barcode integration, perishable expiry tracking, direct farmer batch codes, and organic receipts.',
    keyFeatures: ['Perishable Inventory Batches', 'Barcode & Weight Support', 'Farmer Supplier Records', 'Eco-Receipt Invoicing'],
    sampleGst: '29AABCE6789M1Z3',
    sampleEmailPrefix: 'organic.pantry',
    sampleEmailDomain: 'earthharvest.org',
    samplePhone: '+91 98453 44556',
    sampleAddress: '15 Victoria Road, Richmond Town, Bangalore',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'retail_pharmacy_chemist',
    name: 'MediQuick 24/7 Retail Chemist & Drugstore',
    model: 'Pharmacy & Wellness Healthcare Store',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '💊',
    badge: 'Retail Pharmacy',
    tagline: 'Prescription medicines, surgical supplies, OTC healthcare and baby nutrition',
    description: 'Batch and expiry date tracking on medicine barcodes, schedule drug record tags, and quick customer checkout.',
    keyFeatures: ['Medicine Batch & Expiry Tracking', 'Prescription Verification Tag', 'Fast Chemist Barcode POS', 'GST Tax Slab Invoicing'],
    sampleGst: '07AABCP0123N1Z7',
    sampleEmailPrefix: 'pharmacist.lead',
    sampleEmailDomain: 'mediquickchemist.in',
    samplePhone: '+91 98114 55667',
    sampleAddress: 'Shop 8, Ring Road Market, Lajpat Nagar 4, New Delhi',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'retail_electronics_store',
    name: 'TechWorld Electronics & Audio Superstore',
    model: 'Consumer Electronics & Gadget Retailer',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '🎧',
    badge: 'Electronics Store',
    tagline: 'Laptops, smartphones, wireless audio, gaming consoles and smart home tech',
    description: 'High-value serial number tracking upon checkout, EMI/card tender options, extended warranty add-ons, and supplier POs.',
    keyFeatures: ['Serial Number Scan at Checkout', 'Multi-Tender Payments (Card/UPI)', 'High-Value Stock Ledger', 'Instant GST Tax Invoices'],
    sampleGst: '36AABCT4567P1Z1',
    sampleEmailPrefix: 'electronics.store',
    sampleEmailDomain: 'techworldretail.com',
    samplePhone: '+91 98663 66778',
    sampleAddress: 'Opposite Cyber Towers, Hitech City, Hyderabad',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'retail_fashion_boutique',
    name: 'Aura Vogue Designer Apparel & Luxury Boutique',
    model: 'Fashion Apparel, Footwear & Accessories Store',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '👗',
    badge: 'Fashion Boutique',
    tagline: 'Couture ethnic wear, modern luxury streetwear and handcrafted leather shoes',
    description: 'Matrix variants by Size and Color (e.g. S, M, L, XL in Crimson), return/exchange policies, and VIP loyalty discounts.',
    keyFeatures: ['Size/Color Variant Catalog', 'Exchange & Credit Notes', 'Customer Purchase History', 'Designer Discount Codes'],
    sampleGst: '33AABCV8901Q1Z5',
    sampleEmailPrefix: 'boutique.manager',
    sampleEmailDomain: 'auravogue.style',
    samplePhone: '+91 98402 77889',
    sampleAddress: 'Khader Nawaz Khan Road, Nungambakkam, Chennai',
    taxState: 'INTRA_STATE',
  },
  {
    id: 'retail_artisan_cheese',
    name: 'The Gourmet Fromagerie & European Deli',
    model: 'Specialty Cheese, Cold Cuts & Imported Deli',
    category: 'Retail & Supermarket',
    industry: 'RETAIL',
    shopType: 'retail',
    arch: 'RETAIL',
    emoji: '🧀',
    badge: 'Gourmet Deli',
    tagline: 'Artisan aged gouda, parmigiano reggiano, truffle oils and charcuterie',
    description: 'Weighable deli scale items, temperature storage stock notes, specialty import tax rules, and rapid POS bagging.',
    keyFeatures: ['Scale Weight Price Calculator', 'Batch Cold-Chain Storage Log', 'Imported Gourmet SKU Matrix', 'Quick Till Checkout'],
    sampleGst: '27AABCF2345R1Z9',
    sampleEmailPrefix: 'fromagerie.deli',
    sampleEmailDomain: 'gourmetdeli.in',
    samplePhone: '+91 98201 88990',
    sampleAddress: 'Pali Hill Market, Bandra West, Mumbai',
    taxState: 'INTRA_STATE',
  },
];
